name: Test and Generate Documentation

on:
  push:
    branches:
      - "**"

jobs:
  test-and-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install pip-tools and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools --break-system-packages
          pip-sync dev-requirements.txt

      - name: Run pytest
        run: pytest tests/

      - name: Generate documentation (main branch)
        if: github.ref_name == 'main'
        run: |
          mkdir temp-docs
          pdoc --html --output-dir temp-docs --force .  
          rsync -av temp-docs/iac-okta-get-resource/ docs/
          rm -rf temp-docs

      - name: Commit and push documentation
        if: github.ref_name == 'main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update documentation [skip ci]" || echo "No changes to commit"
          git push
